# Generated by Django 3.0.7 on 2020-09-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='code',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='code',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/item/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='itemattributevalue',
            name='item_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_attribute_values', to='sw_catalog.ItemAttribute', verbose_name='Атрибут товару'),
        ),
    ]
