# Generated by Django 3.0 on 2020-09-02 14:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sw_catalog', '0002_auto_20200902_1310'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='itemcategory',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
