# Generated by Django 3.0.7 on 2020-09-02 15:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sw_catalog', '0003_auto_20200902_1414'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='itemcategory',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
